import FlexibleWorkflowModeImg  from "./sections/flexible-workflow-mode.png";
import PowerfulPluginImg from "./sections/powerful-plugin.png";
import LoadAnyModelImg from "./sections/load-any-model.png";
import VideoGernerationImg from "./sections/video-gerneration.webp";
import WorkflowManagementImg from "./sections/workflow-management.png";
import SupportTemplatesImg from "./sections/support-templates.png";
import AccompanyingTutorialImg from "./sections/accompanying-tutorial.png";
import GithubPageImg from "./sections/github-page.png";
import DownloadImg from "./sections/download.png";
import ComfyanonymousImg from "./sections/comfyanonymous.png";
import DorotaLunaImg from "./sections/dorotaLuna.jpeg";
import LtdrdataImg from "./sections/ltdrdata.jpeg";
import CubiqImg from "./sections/cubiq.jpeg";
import Fannovel16Img from "./sections/fannovel16.png";
import ZhoImg from "./sections/zho.png";


import Image from "next/image";
import { h } from "nextra/dist/types-c8e621b7";
import { transform } from "next/dist/build/swc";
import { TutorialsInfo } from "./tutorials-data";

export function Sections() {
  return (
    <div className="sections">
      <div className="section">
        <h2><span className="color-text">Better control</span> the AI's output</h2>
        <p className="description" style={{margin: "24px auto 44px auto"}}>Our product is different from those you've used before. It offers a workflow approach that allows you to better manage the outcomes generated by AI.</p>
      </div>

      <div className="flexbox">
        <div className="box">
          <LoadAnyModel />
          <VideoGerneration />
        </div>
        <PowerfulPlugin />
      </div>
      <FlexibleWorkflowMode />

      <div className="section" style={{marginTop: "140px"}}>
        <h2>Easy to <span className="color-text">use</span> and <span className="color-text">learn</span></h2>
        <p className="description" style={{margin: "24px auto 44px auto"}}>We've made numerous enhancements to our product to lower the barriers to entry for everyone. Additionally, we provide comprehensive tutorials for learning and guidance.</p>
      </div>

      <div className="flexbox">
        <WorkflowManagement />
        <SupportsTemplates />
      </div>
      <div className="box">
          <AccompanyingTutorial />
      </div>

      <div className="section" style={{marginTop: "140px"}}>
        <h2>We offer an <span className="color-text">open-source version</span></h2>
      </div>

      <div className="flexbox">
        <SpecialThanks />
        <OpenSourceVersion />
      </div>

    </div>
  )
}

function PowerfulPlugin() {
  return (
    <div className="section-block debug-mode" style={{backgroundColor:"transparent"}}>
      <GradientBg/>
      <h2>Powerful Plugin System</h2>
      <p className="description">Thanks to the open-source community, our product boasts a robust plugin system. Through these plugins, you can tap into a variety of the latest AI technologies such as ControlNet, IPAdapter, and InstantID.</p>
      <Image src={PowerfulPluginImg.src} width={800} height={1024} alt="powerful plugin sysetm" style={{margin: "60px 0px 0px 20px", paddingBottom:"20px", transform:"scale(1.1)"}}/>
    </div>
  )
}

function LoadAnyModel() {
  return (
    <div className="section-block rich-templates">
      <h2>Load Any AI Model</h2>
      <p className="description">You can use all the current open-source models available on the market with our product, such as SD 1.5, SDXL, and even Playground.</p>
      <Image src={LoadAnyModelImg.src} width={800} height={1024} alt="powerful plugin sysetm" style={{margin: "40px 0px 0px 0px",transform:"scale(1.05)"}}/>
    </div>
  )
}

function VideoGerneration() {
  return (
    <div className="section-block workflow-management" style={{display: "flex"}}>
      <div>
        <h2>Video Generation</h2>
        <p className="description" style={{padding:"0px 10px 0px 0px"}}>Besides creating images, you can also generate videos.</p>
      </div>
      <Image src={VideoGernerationImg.src} width={400} height={1024} alt="powerful plugin sysetm" style={{borderRadius: "10px"}}/>
    </div>
  )
}

function FlexibleWorkflowMode() {
    const backgroundImageStyle = {
      backgroundImage: `url(${FlexibleWorkflowModeImg.src})`,
      backgroundSize: '100% 100%',
      backgroundRepeat: 'no-repeat',
      backgroundPosition: 'center',
      height: '700px',
    };
  return (
    <div className="section-block flexibleworkflow" style={backgroundImageStyle}>
      <h2 style={{marginBottom:'10px'}}>Flexible Workflow Mode</h2>
      <p className="description" style={{color:'white', maxWidth:'100%', marginTop:'10px'}}>By connecting nodes, you can influence the AI's output. For example, by adding a LoRA node, you can direct the AI to generate images in a specific style, or by adding an InstantID node, you can have the AI create faces identical to the original image.</p>
    </div>
  )
}

function WorkflowManagement() {
  return (
    <div className="section-block workflow-management">
      <h2>Workflow Management</h2>
      <p className="description">Manage your Workflow more conveniently, and every change you make will be automatically saved, so you no longer need to manually export and save your workflow.</p>
      <Image src={WorkflowManagementImg.src} width={500} height={1024} alt="workflow management" style={{margin: "100px 0px 80px 40px",transform:"scale(1.8)"}}/>
    </div>
  )
}

function SupportsTemplates() {
  return (
    <div className="section-block supports-templates" style={{backgroundColor:"transparent"}}>
      <GradientBg />
      <h2>Supports Templates</h2>
      <p className="description">Setting up a workflow is tedious? The product supports one-click use of templates, eliminating the hassle of building workflows.</p>
      <Image src={SupportTemplatesImg.src} width={500} height={1024} alt="workflow management" style={{margin: "20px 0px 20px 40px",transform:"scale(1.2)"}}/>
    </div>
  )
}

function AccompanyingTutorial() {
  return (
    <div className="section-block accompanying-tutorial" style={{display: "flex"}}>
      <div>
        <h2>Accompanying Tutorial</h2>
        <p className="description">All templates come with accompanying text tutorials and video demonstrations.</p>
      </div>

      {/* <Image src={AccompanyingTutorialImg.src} width={900} height={100} alt="powerful plugin sysetm" style={{margin: "10px 0px 10px 100px", transform:"scale(1.1)"}}/> */}
    </div>
  )
}

function SpecialThanks() {
  return (
    <div className="section-block supports-templates">
      <h2>Special Thanks</h2>
      <p className="description">The reason Comflowy boasts such powerful capabilities is largely thanks to the robust open-source community, with a special shoutout to ComfyUI. That's why we've also offered an open-source version, which has already seen nearly 20 iterations.</p>
      <div style={{display: "flex", alignItems:"center", margin:"40px 0px"}}>
         <a href="https://github.com/comfyanonymous/ComfyUI" target="_blank">
          <Image src={ComfyanonymousImg.src} width={120} height={100} alt="download" style={{borderRadius: "200px", transform:"scale(0.7)"}}/>
         </a>
         <a href="https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation" target="_blank">
          <Image src={DorotaLunaImg.src} width={120} height={100} alt="download" style={{borderRadius: "200px", transform:"scale(0.7)"}}/>
         </a>
         <a href="https://github.com/ltdrdata/ComfyUI-Manager" target="_blank">
          <Image src={LtdrdataImg.src} width={120} height={100} alt="download" style={{borderRadius: "200px", transform:"scale(0.7)"}}/>
         </a>
         <a href="https://github.com/cubiq" target="_blank">
          <Image src={CubiqImg.src} width={120} height={100} alt="download" style={{borderRadius: "200px", transform:"scale(0.7)"}}/>
         </a>
         <a href="https://github.com/Fannovel16/comfyui_controlnet_aux" target="_blank">
          <Image src={Fannovel16Img.src} width={120} height={100} alt="download" style={{borderRadius: "200px", transform:"scale(0.7)"}}/>
         </a>
         <a href="https://github.com/ZHO-ZHO-ZHO" target="_blank">
          <Image src={ZhoImg.src} width={120} height={100} alt="download" style={{borderRadius: "200px", transform:"scale(0.7)"}}/>
         </a>
      </div>
    </div>
  )
}

function OpenSourceVersion() {
  return (
    <div className="section-block supports-templates">
      <h2>Open-source Version</h2>
      <div style={{display: "flex", alignItems:"center"}}>
        <a href="https://github.com/6174/comflowyspace/releases" target="_blank">
          <Image src={DownloadImg.src} width={260} height={1024} alt="download" style={{margin:"20px 20px 20px 0px"}}/>
        </a>
        <a href="https://github.com/6174/comflowyspace" target="_blank">
          <Image src={GithubPageImg.src} width={260} height={1024} alt="github page" />
        </a>
      </div>
    </div>
  )
}

function GradientBg() {
  return (
    <div className="gradient-bg">
      <svg width="1347" height="648" viewBox="0 0 1347 648" fill="none" xmlns="http://www.w3.org/2000/svg">
        <g opacity="0.5">
          <rect opacity="0.5" x="293.147" y="237.404" width="876.705" height="173.263" rx="86.6316" stroke="url(#paint0_radial_1237_15621)" strokeWidth="3" />
          <rect opacity="0.5" x="275.292" y="220.73" width="912.417" height="206.61" rx="103.305" stroke="url(#paint1_radial_1237_15621)" strokeWidth="3" />
          <rect opacity="0.5" x="309.813" y="255.269" width="843.374" height="137.534" rx="68.7671" stroke="url(#paint2_radial_1237_15621)" strokeWidth="3" />
          <rect opacity="0.4" x="216.312" y="167.809" width="1028.75" height="312.383" rx="156.191" stroke="url(#paint3_radial_1237_15621)" strokeWidth="3" />
          <rect opacity="0.4" x="255.368" y="203.139" width="950.635" height="241.723" rx="120.862" stroke="url(#paint4_radial_1237_15621)" strokeWidth="3" />
          <rect opacity="0.4" x="237.468" y="185.904" width="986.437" height="276.191" rx="138.096" stroke="url(#paint5_radial_1237_15621)" strokeWidth="3" />
          <rect opacity="0.3" x="196.783" y="147.989" width="1069.43" height="352.021" rx="176.011" stroke="url(#paint6_radial_1237_15621)" strokeWidth="3" />
          <rect opacity="0.3" x="174.001" y="132.479" width="1115" height="383.043" rx="191.521" stroke="url(#paint7_radial_1237_15621)" strokeWidth="3" />
          <rect opacity="0.2" x="152.845" y="116.968" width="1157.31" height="414.064" rx="207.032" stroke="url(#paint8_radial_1237_15621)" strokeWidth="3" />
          <rect opacity="0.1" x="104.023" y="80.7769" width="1254.95" height="486.447" rx="243.223" stroke="url(#paint9_radial_1237_15621)" strokeWidth="3" />
          <rect opacity="0.1" x="131.689" y="102.319" width="1199.62" height="443.362" rx="221.681" stroke="url(#paint10_radial_1237_15621)" strokeWidth="3" />
          <rect opacity="0.05" x="35.6748" y="38.5532" width="1391.65" height="570.894" rx="285.447" stroke="url(#paint11_radial_1237_15621)" strokeWidth="3" />
          <rect opacity="0.05" x="73.1035" y="62.6812" width="1316.79" height="522.638" rx="261.319" stroke="url(#paint12_radial_1237_15621)" strokeWidth="3" />
          <rect opacity="0.05" x="1.5" y="1.5" width="1460" height="645" rx="322.5" stroke="url(#paint13_radial_1237_15621)" strokeWidth="3" />
        </g>
        <defs>
          <radialGradient id="paint0_radial_1237_15621" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(731.5 324.036) rotate(90) scale(88.1316 439.852)">
            <stop stopColor="#2BCBBB" />
            <stop offset="1" stopColor="#2AAFF7" />
          </radialGradient>
          <radialGradient id="paint1_radial_1237_15621" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(731.5 324.036) rotate(90) scale(104.805 457.708)">
            <stop stopColor="#2BCBBB" />
            <stop offset="1" stopColor="#2AAFF7" />
          </radialGradient>
          <radialGradient id="paint2_radial_1237_15621" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(731.5 324.036) rotate(90) scale(70.2671 423.187)">
            <stop stopColor="#2BCBBB" />
            <stop offset="1" stopColor="#2AAFF7" />
          </radialGradient>
          <radialGradient id="paint3_radial_1237_15621" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(730.686 324.001) rotate(90) scale(157.691 515.874)">
            <stop stopColor="#2BCBBB" />
            <stop offset="1" stopColor="#2AAFF7" />
          </radialGradient>
          <radialGradient id="paint4_radial_1237_15621" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(730.686 324) rotate(90) scale(122.362 476.818)">
            <stop stopColor="#2BCBBB" />
            <stop offset="1" stopColor="#2AAFF7" />
          </radialGradient>
          <radialGradient id="paint5_radial_1237_15621" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(730.686 324) rotate(90) scale(139.596 494.719)">
            <stop stopColor="#2BCBBB" />
            <stop offset="1" stopColor="#2AAFF7" />
          </radialGradient>
          <radialGradient id="paint6_radial_1237_15621" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(731.5 324) rotate(90) scale(177.511 536.216)">
            <stop stopColor="#2BCBBB" />
            <stop offset="1" stopColor="#2AAFF7" />
          </radialGradient>
          <radialGradient id="paint7_radial_1237_15621" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(731.5 324) rotate(90) scale(193.021 558.999)">
            <stop stopColor="#2BCBBB" />
            <stop offset="1" stopColor="#2AAFF7" />
          </radialGradient>
          <radialGradient id="paint8_radial_1237_15621" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(731.5 324) rotate(90) scale(208.532 580.155)">
            <stop stopColor="#2BCBBB" />
            <stop offset="1" stopColor="#2AAFF7" />
          </radialGradient>
          <radialGradient id="paint9_radial_1237_15621" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(731.5 324) rotate(90) scale(244.723 628.976)">
            <stop stopColor="#2BCBBB" />
            <stop offset="1" stopColor="#2AAFF7" />
          </radialGradient>
          <radialGradient id="paint10_radial_1237_15621" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(731.5 324) rotate(90) scale(223.181 601.311)">
            <stop stopColor="#2BCBBB" />
            <stop offset="1" stopColor="#2AAFF7" />
          </radialGradient>
          <radialGradient id="paint11_radial_1237_15621" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(731.5 324) rotate(90) scale(286.947 697.325)">
            <stop stopColor="#2BCBBB" />
            <stop offset="1" stopColor="#2AAFF7" />
          </radialGradient>
          <radialGradient id="paint12_radial_1237_15621" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(731.5 324) rotate(90) scale(262.819 659.896)">
            <stop stopColor="#2BCBBB" />
            <stop offset="1" stopColor="#2AAFF7" />
          </radialGradient>
          <radialGradient id="paint13_radial_1237_15621" cx="0" cy="0" r="1" gradientUnits="userSpaceOnUse" gradientTransform="translate(731.5 324) rotate(90) scale(324 731.5)">
            <stop stopColor="#2BCBBB" />
            <stop offset="1" stopColor="#2AAFF7" />
          </radialGradient>
        </defs>
      </svg>

    </div>
  )
}
